### ISSUE TITLE
I encountered some issues while running

### ISSUE THREAD

**Issue by pihkhggc** [masafumiendo/benchnav#11]
To train the terrain classifier:&&To train the slip regressors:
When I run here，
![4e81018f65bd97d6817374d3251701d](https://github.com/masafumiendo/benchnav/assets/132460789/371d650c-49a1-4f0d-9276-970ae06fedb5)
![738877a90b13935899d8af061df0c89](https://github.com/masafumiendo/benchnav/assets/132460789/c5e7a2d9-74d4-443e-9bc3-1e832cc76a81)

I am using the CPU version without GPU support.
If you could give me some help, I would be extremely grateful.
Best wish!

**Comment by masafumiendo** [comment]
Thank you for your inquiry! It seems like the device is set as "cuda:0" while running the scripts on a cpu-only environment. You can specify "cpu" for the argument of the main method.
