### ISSUE TITLE
Cannot run notebook in docker container

### ISSUE THREAD

**Issue by UraraKono** [masafumiendo/benchnav#9]
Hi,
I opened the benchnav directory with VScode using dev-cpu container.
I tried to run the cells of notebooks/tutorial_no1_environments.ipynb, but vscode asked me which kernel to use such as python 3.10 or 3.8.
I tried both, but it returned the error "Running cells with "Python 3.10.14" requires the ipykernel package.
It seems ipynb files are not run in the container.
So I had to copy and paste the codes into a new python file and ran it in the container's terminal.

Could you fix this issue?

**Comment by masafumiendo** [comment]
Hi, thank you for your feedback!

We modified our repository as follows:
- fix this repo to run tutorial notebooks with docker (done by K. Honda @kohonda thank you so much!)
- fix this repo to work only with CPU

Can you run `make build-cpu` (`make build-gpu` if you have GPU environments) again to check if you can run notebook tutorials with docker? If any problem remains, please let me know!
